import Head from 'next/head';
import Image from 'next/image';
import UserResults from '../components/users/UserResult';
import UserSearch from '../components/users/UserSearch';

import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>GitHub Finder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <UserSearch />
      <UserResults />
    </div>
  );
}
